<?php

use App\Models\City;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $cities = [
            ['ar'=>'الرياض','en'=>'Riyadh'],
            ['ar'=>'الدمام','en'=>'Dammam'],
            ['ar'=>'مكة','en'=>'Mecca'],
            ['ar'=>'بقيق','en'=>'Abqyq'],
            ['ar'=>'عين دار الجديدة','en'=>'Eayan dar aljadida'],
            ['ar'=>'العيون','en'=>'Aleuyun'],
            ['ar'=>'الهفوف','en'=>'AlHofuf'],
            ['ar'=>'الوزية','en'=>'Alwazia'],
            ['ar'=>'المبريز','en'=>'Almubriz'],
            ['ar'=>'القرة','en'=>'Alqurra'],
            ['ar'=>'السليمانية','en'=>'Alsulmania'],
            ['ar'=>'العمران','en'=>'Aleumran'],
            ['ar'=>'الاكحل','en'=>'Aleaqir'],
            ['ar'=>'الجفر','en'=>'Aljafr'],
            ['ar'=>'مدينه الخبر','en'=>'Khobar'],
            ['ar'=>'الظهران','en'=>'Dhahran'],
            ['ar'=>'القطيف','en'=>'Qatif'],
            ['ar'=>'سيهات','en'=>'Sihat'],
            ['ar'=>'النبية','en'=>'Nabiyah'],
            ['ar'=>'تاروت','en'=>'Tarout'],
            ['ar'=>'عنك','en'=>'Anak'],
            ['ar'=>'الجش','en'=>'Aljish'],
            ['ar'=>'العجم','en'=>'Al Ogam'],
            ['ar'=>'صفوى','en'=>'Safwa'],
            ['ar'=>'خميس مشيط','en'=>'Khamis mushait'],
            ['ar'=>'تانداها','en'=>'Tandaha'],
            ['ar'=>'وادي بن هشبل','en'=>'Wadi bin Hashbal'],
            ['ar'=>'أبها','en'=>'Abha'],
            ['ar'=>'أحد رفيدة','en'=>'Ahad Rafida'],
            ['ar'=>'الوادين','en'=>'Al Waddean'],
            ['ar'=>'سراة عبيدة','en'=>'Sarat Obida'],
            ['ar'=>'محايل عسير','en'=>'Mahayel Aseer'],
            ['ar'=>'رجال الماء','en'=>'Rejal Al Ma\'a'],
            ['ar'=>'تنوما','en'=>'Tanoma'],
            ['ar'=>'بيلسمر','en'=>'Bilasmer'],
            ['ar'=>'بيلامر','en'=>'Bilahmer'],
            ['ar'=>'القويعية','en'=>'Al quwaiiyah'],
            ['ar'=>'جيله','en'=>'Jilah'],
            ['ar'=>'الحاسي','en'=>'Al hasi'],
            ['ar'=>'تعمير','en'=>'Tameer'],
            ['ar'=>'التمرية','en'=>'Temeriyah'],
            ['ar'=>'حوطة سدير','en'=>'Hotat Sudair'],
            ['ar'=>'عشيرة سدير','en'=>'Asheerah Sudayer'],
            ['ar'=>'عودة سدير','en'=>'Awdah Sudayer'],
            ['ar'=>'روضة سدير','en'=>'Roudhah Sudayer'],
            ['ar'=>'سداير','en'=>'Sudayer'],
            ['ar'=>'المعشبة','en'=>'Al Ma`ashabah'],
            ['ar'=>'جلاجل','en'=>'Jalajil'],
            ['ar'=>'المجمعة','en'=>'Majma'],
            ['ar'=>'حرمة','en'=>'Hermah'],
            ['ar'=>'بنبان','en'=>'Banban'],
            ['ar'=>'مزاحمية','en'=>'Muzahmiah'],
            ['ar'=>'قصور المقبل','en'=>'Qusor almoqbel'],
            ['ar'=>'ضرما','en'=>'Dhurma'],
            ['ar'=>'ملحم','en'=>'Mulhem'],
            ['ar'=>'صلبوخ','en'=>'Salbokh'],
            ['ar'=>'القرينة','en'=>'Al Qareenah'],
            ['ar'=>'ثارمادا','en'=>'Tharmada`a'],
            ['ar'=>'أشقر','en'=>'Ushayqer'],
            ['ar'=>'شقراء','en'=>'Shaqra'],
            ['ar'=>'قصب','en'=>'Qasab'],
            ['ar'=>'عيينة','en'=>'Oyaynah'],
            ['ar'=>'حوريمال','en'=>'Horaimal'],
            ['ar'=>'ثادق','en'=>'Thadeq'],
            ['ar'=>'الخوارج','en'=>'Kharij'],
            ['ar'=>'ديليم','en'=>'Daelim'],
            ['ar'=>'حريق','en'=>'Hareeq'],
            ['ar'=>'حوطة بني تميم','en'=>'Howtat bani tamim'],
            ['ar'=>'نعيم','en'=>'Naa\'m'],
            ['ar'=>'الظبيعة','en'=>'Al Dhabe`ah'],
            ['ar'=>'هيت','en'=>'Heet'],
            ['ar'=>'الحزم','en'=>'Al Hazim'],
            ['ar'=>'الحلوة','en'=>'Al Helwah'],
            ['ar'=>'العماجية','en'=>'Al Amajiyah'],
            ['ar'=>'جازان','en'=>'Jazan'],
            ['ar'=>'ابو عريش','en'=>'Abu Arish'],
            ['ar'=>'صبيا','en'=>'Sabya'],
            ['ar'=>'داماد','en'=>'Damad'],
            ['ar'=>'احد المسارحه','en'=>'Ahad Al Masarihah'],
            ['ar'=>'صامطة','en'=>'Samtah'],
            ['ar'=>'بيش','en'=>'Baish'],
            ['ar'=>'هيناكيا','en'=>'Hinakeya'],
            ['ar'=>'راثايا','en'=>'Rathaya'],
            ['ar'=>'السويدرة','en'=>'Suwaidhrah'],
            ['ar'=>'شقران','en'=>'Sheqran'],
            ['ar'=>'مينداسا','en'=>'Mindassah'],
            ['ar'=>'مليليح','en'=>'Mulaylih'],
            ['ar'=>'سلسة','en'=>'Selselah'],
            ['ar'=>'الثماد','en'=>'Al Thamad'],
            ['ar'=>'خيبر','en'=>'Khaybar'],
            ['ar'=>'بير الماشي','en'=>'Bir Al Mashi'],
            ['ar'=>'عشيرة','en'=>'Ushyrah'],
            ['ar'=>'وادي ريم','en'=>'Wadi Reem'],
            ['ar'=>'اليوتامة','en'=>'Alyutamah'],
            ['ar'=>'وادي فورا','en'=>'Wadi Al Fora'],
            ['ar'=>'الأكحل','en'=>'Al Akhal'],
            ['ar'=>'الفريش','en'=>'Al Furaysh'],
            ['ar'=>'المسجيد','en'=>'Al Musayjid'],
            ['ar'=>'بدر','en'=>'Badr'],
            ['ar'=>'ينبع','en'=>'Yanbu'],
            ['ar'=>'الدميرية','en'=>'Ad Dumayriyah'],
            ['ar'=>'الحراره','en'=>'Al Harara'],
            ['ar'=>'مهد دهب','en'=>'Mahd Dahab'],
            ['ar'=>'المدينة المنورة','en'=>'Medina'],
            ['ar'=>'الطائف','en'=>'Taif'],
            ['ar'=>'السيل الكبير','en'=>'As Sail Al Kabeer'],
            ['ar'=>'السيل الصغير','en'=>'As Sail Al Sager'],
            ['ar'=>'الهدا','en'=>'Alhada'],
            ['ar'=>'الشفاء','en'=>'Ashafa'],
            ['ar'=>'خليص','en'=>'Khulais'],
            ['ar'=>'عسفان','en'=>'Asfan'],
            ['ar'=>'ذهبان','en'=>'Dahban'],
            ['ar'=>'ثول','en'=>'Thuwal'],
            ['ar'=>'مدينة الملك عبدالله الاقتصادية','en'=>'King abdullah econ city'],
            ['ar'=>'جدة','en'=>'Jeddah'],
            ['ar'=>'بريدة','en'=>'Buraydah'],
            ['ar'=>'عنيزة','en'=>'Onaizah'],
            ['ar'=>'البدائع','en'=>'albadayie'],
            ['ar'=>'الرس','en'=>'AlRass'],
            ['ar'=>'الشمسية','en'=>'ash shmasiyah'],
            ['ar'=>'الزلفي','en'=>'Az Zulfi'],
            ['ar'=>'الغاط','en'=>'Alghat'],
            ['ar'=>'مليح','en'=>'Maleeh'],
            ['ar'=>'عيون الجواء','en'=>'uyun aljawa'],
            ['ar'=>'البكيرية','en'=>'bukayriah'],
            ['ar'=>'الخبر','en'=>'alkhubara'],
            ['ar'=>'رياض الخبراء','en'=>'riad alkhubara'],
            ['ar'=>'الشحية','en'=>'Al Shehiyah'],
            ['ar'=>'عين بن فهيد','en'=>'ayn bn fuhayd'],
            ['ar'=>'الخصيبة','en'=>'alkhasiybah'],
            ['ar'=>'دندي','en'=>'dayida'],
            ['ar'=>'الباطن','en'=>'albatin'],
            ['ar'=>'طرفيه','en'=>'at turfiyah'],
            ['ar'=>'قصيبة','en'=>'qusaiba'],
            ['ar'=>'المذنب','en'=>'AL mithnab'],
            ['ar'=>'البصير','en'=>'Albaser'],
            ['ar'=>'النبهانية','en'=>'An Nabhaniyah'],
            ['ar'=>'عقلة الصقور','en'=>'Uglat Asugour'],
            ['ar'=>'العمار','en'=>'Al Amaar'],
            ['ar'=>'البتراء','en'=>'Al Petra'],
            ['ar'=>'ثادج','en'=>'Thadij'],
            ['ar'=>'الخشيبى','en'=>'Al Khushaybi'],
            ['ar'=>'الفوارة','en'=>'Al Fawwarah'],
            ['ar'=>'بريدة','en'=>'Buraidah'],
            ['ar'=>'الأحساء','en'=>'Al Ahsa'],
            ['ar'=>'الأحساء','en'=>'AlHasa'],
            ['ar'=>'نجران','en'=>'Najran'],
            ['ar'=>'جيزان','en'=>'jizan'],
            ['ar'=>'الجبيل','en'=>'Jubail'],
            ['ar'=>'تبوك','en'=>'Tabuk'],
            ['ar'=>'الدرعية','en'=>'Ad Diriyah'],
            ['ar'=>'الخراج','en'=>'Alkharaj'],
            ['ar'=>'رأس تنورة','en'=>'Ras Tanura'],
            ['ar'=>'سيهات','en'=>'Saihat'],
            ['ar'=>'بحرة','en'=>'Bahrah'],
            ['ar'=>'عين دار القديمة','en'=>'eayan  dar alqadima '],
            ['ar'=>'يثرب','en'=>'Yathrib'],
            ['ar'=>'فوضى','en'=>'fawada'],
            ['ar'=>'الشهيلي','en'=>'alshahili'],
            ['ar'=>'سالاسيل','en'=>'salasil'],
            ['ar'=>'الصناعية','en'=>'industrial'],
            ['ar'=>'الوديان','en'=>'alwaddean'],
            ['ar'=>'المدينة العسكرية','en'=>'military city'],
            ['ar'=>'الريش','en'=>'alreesh'],
            ['ar'=>'سدير','en'=>'sudayer'],
            ['ar'=>'الفوارة','en'=>'alfawwarah'],
            ['ar'=>'الخشيبي','en'=>'alkhushabi'],
            ['ar'=>'البترا','en'=>'alpetra'],
            ['ar'=>'الاعمار','en'=>'alamaar'],
            ['ar'=>'طريف','en'=>'tarif'],
            ['ar'=>'ابا الورود','en'=>'aba alwuorood'],
            ['ar'=>'الشيحيه','en'=>'al shehiyah'],
            ['ar'=>'حفر الباطن','en'=>'Hafar Al Batin'],
            ['ar'=>'الدوادمي','en'=>'Al Duwadimi'],
            ['ar'=>'بيشة','en'=>'Bisha'],
            ['ar'=>'ليث','en'=>'Laith'],
            ['ar'=>'وادي الدواسر','en'=>'Wadi Ad Dawasir'],
            ['ar'=>'حائل','en'=>'Hail'],
            ['ar'=>'اخرى','en'=>'other'],
            ['ar'=>'المدينة','en'=>'Medina'],
            ['ar'=>'سكاكا','en'=>'Skaka'],
            ['ar'=>'النعيرية','en'=>'nairyah'],
            ['ar'=>'الباحة','en'=>'Al Bahah'],
            ['ar'=>'الخفجي','en'=>'Khafji'],
            ['ar'=>'النماص','en'=>'Al Namas'],
            ['ar'=>'القريات','en'=>'Al Qurayyat'],
            ['ar'=>'LAI','en'=>'LAI'],
            ['ar'=>'القنفذة','en'=>'Al Qunfudhah'],
            ['ar'=>'القصيم','en'=>'Al Qassim'],
            ['ar'=>'حفر الباطن','en'=>'Hafr al-Batin'],
            ['ar'=>'النعيرية','en'=>'Nairyah'],
            ['ar'=>'شرورة','en'=>'Sharurah'],
            ['ar'=>'منطقة الرياض','en'=>'riyadh province'],
            ['ar'=>'عرعر','en'=>'ARAR'],
            ['ar'=>'رابغ','en'=>'Rabigh'],
            ['ar'=>'القريات','en'=>'AlQurayyat'],
            ['ar'=>'الجبيل','en'=>'Jubail Industrial'],
            ['ar'=>'غير معروف','en'=>'Unknown'],
            ['ar'=>'تربة','en'=>'Turbah'],
            ['ar'=>'قرية العليا','en'=>'Qaryat Al Ulya'],
            ['ar'=>'نمرة','en'=>'Namerah'],
            ['ar'=>'المجاردة','en'=>'Almajaridah'],
            ['ar'=>'الافلاج','en'=>'Al Aflaj'],
            ['ar'=>'القريات','en'=>'Al Qurayyat'],
            ['ar'=>'المظيلف','en'=>'Almuzaylif'],
            ['ar'=>'قلوة','en'=>'Qilwah'],
            ['ar'=>'العقيق','en'=>'Al Aqiq'],
            ['ar'=>'عفيف','en'=>'Afif'],
            ['ar'=>'ينبع البحر','en'=>'Yanbu Al Baher'],
            ['ar'=>'منطقة مكة','en'=>'Makkah Province'],
            ['ar'=>'منطقة المدينة','en'=>'Madina Province'],
            ['ar'=>'منطقة تبوك','en'=>'Tabuk Province'],
            ['ar'=>'منطقة عسير ','en'=>'Aseer Province'],
            ['ar'=>'منطقة نجران','en'=>'Najran Province'],
            ['ar'=>'منطقة جزان','en'=>'Jazan Province'],
            ['ar'=>'ام الملح','en'=>'Umm Al Melh'],
            ['ar'=>'منطقة سكاكا','en'=>'Sakaka Province'],
            ['ar'=>'منطقة حائل','en'=>'Hail Province'],
            ['ar'=>'منطقة القصيم','en'=>'Al Qassim Province'],
            ['ar'=>'المنطقة الشرقية','en'=>'Eastern Province'],
            ['ar'=>'سبت العلايه','en'=>'Sabt Alalayah'],
            ['ar'=>'العوامية','en'=>'Al Awamiyah'],
            ['ar'=>'املج','en'=>'Umluj'],
            ['ar'=>'رماح','en'=>'Rumah'],
            ['ar'=>'الحاوي / الطائف','en'=>'Hawea/Taif'],
            ['ar'=>'الحائط','en'=>'Al Hait'],
            ['ar'=>'الدائر','en'=>'Addayer'],
            ['ar'=>'الجموم','en'=>'Al Jumum'],
            ['ar'=>'حبونا','en'=>'Hubuna'],
            ['ar'=>'الجوف','en'=>'Al Jowf'],


        ];

        foreach($cities as $city){
             City::create([
                'name' => $city,
                'parent_id'=>0,
                'country_id'=>1,
                'status'=>'enabled'
            ]);
        }

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {

    }
};
